name: clickandgoapp
description: Application for scanning products in the store and online payment (prototype)

version: 1.0.2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  cupertino_icons: ^0.1.2
  flutter_svg: 0.17.4
  fluttertoast: 4.0.1
  shared_preferences: 0.5.7
  gson: 0.1.4

  camera:
  path_provider: ^1.6.5
  path:
  barcode_scan: 3.0.0

  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: false
  ios: false
  image_path: "assets/splash_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/splash_background.jpg
    - assets/splash_icon.png
